### ISSUE TITLE
Info of the API of Qobuz

### ISSUE THREAD

**Issue by carrieroent** [iamdb/hifi.rs#131]
The API of Qobuz was previously public. At some point it was closed and nowadays only a few people can get docs and keys to it by request. However, after a quick glance, the API seems very similar to what it was years ago. Information about this could be documented in this issue.

Here's what I found: 
 - On Wayback Machine official Qobuz API documentation: [GitHub - Qobuz/api-documentation: Qobuz Official API documentation](https://web.archive.org/web/20180611030533/https://github.com/Qobuz/api-documentation)
 - On Qobuz.com: [QobuzAPI-TermsofUse.pdf](http://static.qobuz.com/apps/api/QobuzAPI-TermsofUse.pdf)
 - On Rapid API blog: [Qobuz API (Overview, SDK Documentation & Alternatives) | RapidAPI](https://rapidapi.com/blog/directory/qobuz/)
 - On GitHub one project: [taschenb/python-qobuz: Unoffical API for Qobuz music streaming service.](https://github.com/taschenb/python-qobuz)

**Comment by iamdb** [comment]
Why are you putting all of this information here? What does this have to do with my application?

You're adding all of this stuff to document things that I already researched when writing this. If there's a specific problem with the application, please let me know. Otherwise, please don't create issues like this. I already asked you to consolidate this conversation into one issue.
