### ISSUE TITLE
question - how to play artist most popular

### ISSUE THREAD

**Issue by LTSCommerce** [iamdb/hifi.rs#160]
eg https://play.qobuz.com/artist/609181

there is a play button on the web player, but if I paste the URL it doesn't play. Is there any way to work around this?

**Comment by eldorel** [comment]
From a few minutes poking at it I don't think the data used to sort the "most popular" section of the artist pages is provided via API, which would make that a little difficult.
  
(the product_sales_factors_* are all blank in iamdb's scraped data and in my tests and the popularity field is either unused and defaults to '0' or they're relative to all music on the platform and I'm just unable to think of anything that would qualify.)

It might be possible to add a function to the "playlist" CLI option that scrapes the most popular track list from the artist page and creates a new play queue on the fly , but that would require an http handler on top of the api/json handler. (and thus fragile and prone to breaking if the page layout changes.) 

So unless I'm missing something in the API data, the best option would be to add the most popular to your queue, save that to a playlist, and then use the playlist link in hifi.rs.

**Comment by iamdb** [comment]
@eldorel is pretty much right, however, I think the most popular might be available through the API since I haven't ported over everything. I can add more endpoints to the API client if they are available there is just work to be done to uncover them all.

Also, the current goal of this project isn't to duplicate the functionality of the official Qobuz player, but rather to provide some basic functionality that can be built upon within a larger application.

It's not in an good state at the moment, but the cli app will also return raw data from the API. The idea was to allow someone to search for something, pipe that into another interface (Roffi, for example) and then use that output as an argument to another command to play.
